<h2>Edit user</h2>
<hr>
<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">

    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" required>
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <p><?= $errors['nickname'] ?></p>
        <?php endif; ?>
    </div>

    <div>
        <label>
            Email:
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" required>
        </label>
        <?php if (isset($errors['email'])): ?>
            <p><?= $errors['email'] ?></p>
        <?php endif; ?>
    </div>

    <button type="submit">Update</button>
</form>