<h2>New user</h2>
<hr>
<form action="/users" method="post">
    <div>
        <label>
            Nickname:
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>" required>
        </label>
        <?php if (isset($errors['nickname'])): ?>
            <p><?= $errors['nickname'] ?></p>
        <?php endif; ?>
    </div>

    <div>
        <label>
            Email:
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?>" required>
        </label>
        <?php if (isset($errors['email'])): ?>
            <p><?= $errors['email'] ?></p>
        <?php endif; ?>
    </div>

    <button type="submit">Submit</button>
</form>